### ISSUE TITLE
google group posting disabled?

### ISSUE THREAD

**Issue by wmacgyver** [rapidoid/rapidoid#102]
I just tried to post to the google group, and it failed. I couldn't do it either using the email interface nor the web interface.

looking at the group, it looks like it's set to
============
Access
Anyone can view content.
Anyone can apply to join.
Only managers can post.
Only members can view the list of members.
============

**Comment by nmihajlovski** [comment]
Thanks, I had accidentally mis-configured the permissions, trying to prevent spam. I fixed this now.
