### ISSUE TITLE
Couldn't load template: error.html?

### ISSUE THREAD

**Issue by wmacgyver** [rapidoid/rapidoid#103]
I just upgraded to 5.8

I'm only using http-server, since it's just REST only app

since upgrade I notice with every request, I get

Caused by: java.lang.RuntimeException: Couldn't load template: error.html
in error log

I assume this is because of the new template engine that's in place.

is this an intended change of behavior?

**Comment by korri123** [comment]
Create a file called error.html with your other templates, it should fix it.

**Comment by wmacgyver** [comment]
@korri123 I know that would. that's not the reason I'm asking the question. for a REST app, it's possible that you may not have template. or may not use the builtin template engine that came with rapidoid. 

yes I can create the file to make the error go away, but my question is, is this change intentional? because a new user that is trying rapidoid for the first time most likely won't have this file, and throwing up error on first contact isn't a good experience.

**Comment by nmihajlovski** [comment]
Hi, this is not intentional, thanks for reporting it. I will fix it and release 5.2.9 this weekend.

**Comment by wmacgyver** [comment]
@nmihajlovski works great. error went away. thank you.

**Comment by nmihajlovski** [comment]
Great, thanks!
