### ISSUE TITLE
Massive file descriptor usage detected on CentOS 7.2 and Ubuntu 14.04

### ISSUE THREAD

**Issue by sagnitude** [rapidoid/rapidoid#105]
I noticed that on CentOS 7.2 systems, rapidoid is using many file descriptors while handling requests.

I use `lsof | wc -l` to monitor opened file descriptors.

Tested rapidoid version: 5.3.2
Tested JDK: Oracle JDK 1.7 and 1.8 (64bit).

Tested server code:

```
public class RapidoidRunner {
    public static void main(String[] args) {
        On.port(8888);
        On.get("/size").json(new OneParamLambda<String, String>() {
            @Override
            public String execute(String param) throws Exception {
                return "Hello world";
            }
        });
    }
}
```

The following tests are repeated for several times and the results are almost the same. So the newly created file descriptors should be related to the tested server.

|Tested Machine|Java Version|System Verson (Kernel Version)|File descriptor count before program start| File descriptor count after program start| Final file descriptor count while keep refreshing `localhost:8888/size` in browser | `ulimit -Hn`| `ulimit -Sn`|
|-|-|-|-|-|-|-|-|
|1|7u55|CentOS 6.8 (2.6.32-642) |1957|2003|2005|655350|655350|
|2|7u55|CentOS 6.5 (2.6.32-421) |3711|3813|3817|655350|655350|
|2|8u60|CentOS 6.5 (2.6.32-421) |3708|3816|3816|655350|655350|
|3|7u79|CentOS 7.2 (3.10.0-327) |41887|54395|82279|655350|265535|
|3|8u60|CentOS 7.2 (3.10.0-327) |41911|55843|83362|655350|265535|
|4|8u111|Ubuntu 14.04.3 LTS (3.19.0-25) |63185|68911|85224|4096|1024|
|5|8u66|Ubuntu 14.04.3 LTS (3.16.0-53) |9337|12847|24714|4096|1024|
|6|7u79|CentOS 7.2 (3.10.0-327) |29529|41830|69246|4096|1024|
|6|8u60|CentOS 7.2 (3.10.0-327) |29272|43151|70567|4096|1024|

In CentOS 7.2 systems, simply starting the server costs about 14k file descriptors and serving a simple "Hello world" service will cost up to 30k file descriptors.
In Ubuntu 14.04.3 systems the cost was lower: 3k to 5k FDs for server startup and 12k to 13k FDs for serving "Hello World".
This cost seems a bit too high.
But in CentOS 6.x systems the cost was very low, is this the expected behavior?

The attached files are the main differences of `lsof` outputs.

[new_openfiles_during_server_startup_centos_7_2.txt](https://github.com/rapidoid/rapidoid/files/830641/new_openfiles_during_server_startup_centos_7_2.txt)
[new_openfiles_during_server_startup_ubuntu.txt](https://github.com/rapidoid/rapidoid/files/830643/new_openfiles_during_server_startup_ubuntu.txt)
[new_openfiles_while_serving_requests_ubuntu.txt](https://github.com/rapidoid/rapidoid/files/830655/new_openfiles_while_serving_requests_ubuntu.txt)
[new_openfiles_while_serving_requests_centos_7_2.txt](http://up.sagnitude.com/new_openfiles_while_serving_requests_centos_7_2.txt)

**Comment by nmihajlovski** [comment]
Thank you for the detailed report. I am investigating this now...

**Comment by nmihajlovski** [comment]
Looks like they are the same file descriptors, just repeating in the list many times - for each thread. 
E.g. in new_openfiles_while_serving_requests_centos_7_2.txt there are 384 threads x 107 descriptors in average, but the number of unique descriptors seems to be 217:

```
cat new_openfiles_while_serving_requests_centos_7_2.txt | grep 15278 | cut -d' ' -f1-7,9- | sort | uniq | wc -l
```

Can you please check the number of open file descriptors using:
`ls /proc/<process-id>/fd | wc -l`

**Comment by sagnitude** [comment]
The result is 84. I checked the versions of `lsof` I used.

|Tested machine| lsof version|
|-|-|
|1|4.82|
|2|4.82|
|3|4.87|
|4|4.86|
|5|4.86|
|6|4.87|

It seems in some version between (4.82, 4.86], lsof started to display open files per thread. But I can't find this in the official changlog.

I found a related issue here https://github.com/draios/sysdig/issues/300 .

**Comment by nmihajlovski** [comment]
Thanks, it's good to know that!

**Comment by jedy-tian** [comment]
同一台server，运行不同版本的lsof 运行时间和得出的结果是不同的，究其原因是因为，新版本的lsof 默认打印TID（-K 参数）， 
更坑的是这个参数不可关闭。就是说-K 参数默认开启，还不能关闭，这个参数就是个摆设 


1、抓取进程连接数，使用lsof -p pid 或 ls /proc/$pid/fdinfo/ | grep '^[0-9]'| wc 
2、抓取系统连接数，cat /proc/sys/fs/file-nr 
3、lsof -ad^0 |wc
