### ISSUE TITLE
Async requests behave strange

### ISSUE THREAD

**Issue by Wick3r** [rapidoid/rapidoid#106]
First of all: I am not sure if this is a bug in the framework or one in front of the display..

Assume the following code, which should answer a request after a 5 second delay:

```
On.get("/id").plain( (Req req) -> {
            req.async();
            Jobs.after(5).seconds(() -> {
                req.response().result("Hello World").done();
            });
            return req;
        });
```

Request: `http://localhost/id?value=123` (both requests are identically)
I do start two requests "simultaneous" from my webbrowser - the first response comes after 5 seconds, the second one after additional 5 seconds.

Request 1: `http://localhost/id?value=123`  Request 2: `http://localhost/id?value=333`
I do start two requests "simultaneously" from my webbrowser - both responses come in after 5 seconds ("simultaneous").

**Comment by nmihajlovski** [comment]
This is a browser thing. Tracking the requests in the browser shows the second request starts only after the first is complete.

**Comment by Wick3r** [comment]
Confirmed that this is a browser thing. Thanks for helping out!
