### ISSUE TITLE
Chrome reports https://www.rapidoid.org as insecure

### ISSUE THREAD

**Issue by hestad** [rapidoid/rapidoid#111]
Don't know where else to post this. Move/delete it if it's unrelated to this github repo.

**Comment by nmihajlovski** [comment]
Thanks for reporting this, I will take care of it soon...

**Comment by nmihajlovski** [comment]
This is fixed now.

**Comment by hestad** [comment]
I think it's complaining about an image as well? Perhaps the svg?
