### ISSUE TITLE
benchmark question

### ISSUE THREAD

**Issue by lanphan** [rapidoid/rapidoid#113]
Hi,
I see that Rapidoid got a very impressive benchmark in Round 11 & Round 12 / 2016. However, the result in Round 13 / 2016 was dropped drastically ... Is there any reason for this drop?

I'm looking for a high performance web framework, and see that Rapidoid is a very good one ... Just benchmark seems not correct in Round 13, so that I post question here.

**Comment by nmihajlovski** [comment]
Basically Rapidoid's security measures (pipeline limits) blocked the requests from processing for the Plaintext test. The pipeline limit was set to 10 as a default, and Round 13 used pipeline size of 16. Also, previously the Techempower guys had accidentally broken Rapidoid's benchmark implementation, so it didn't execute in the Preview run, thus I didn't really have a chance to investigate and fix it on time.

This is corrected now in Round 14 (preview):
https://www.techempower.com/benchmarks/previews/round14/#section=data-r14&hw=ph&test=plaintext
