### ISSUE TITLE
RouteOptions.managed() undocumented

### ISSUE THREAD

**Issue by mooman219** [rapidoid/rapidoid#116]
Requesting some background on .managed() for RouteOptions. Since it's being used in Techempower's benchmark yet is left unreferenced on Rapidoid's home page, it doesn't appear to be idiomatic rapidoid and exposes a special striped implementation. It would be nice to know what limitations that stripped implementation restricts on to achieve the performance that is shows in benchmarks.

**Comment by nmihajlovski** [comment]
This was elaborated on the mailing list, I will put it in the docs today:

The request processing can be done in a "managed" and "unmanaged" way.
 - Managed (the default): each request will be handled inside a job executed on the executor service (using Jobs.*). - this is the most powerful option, featuring transaction management and access control.
 - Unmanaged: every request is handled on the I/O thread that read it - the fastest option, as long as it's non-blocking.

E.g. on a 8-core machine there would be 8 I/O threads and 64/128/256/512/1024 job executor (worker) threads.

**Comment by nmihajlovski** [comment]
Please take a look at the new docs:
http://www.rapidoid.org/docs.html#_performance_and_scalability

**Comment by mooman219** [comment]
That looks awesome! Thank you.
