### ISSUE TITLE
getMethodParameterNames can't retrieve the parameter names

### ISSUE THREAD

**Issue by richarddd** [rapidoid/rapidoid#122]
Hi,

`names` array is becomes empty after trying to resolve using `codeAttribute != null` block

Debugging and settings correct names explicitly works. 

Bug in:

```
int index = i - offset;
String var = attr.variableName(i);
if (index >= 0 && index < names.length && !"this".equals(var)) {
   names[index] = var;
}
```

`offset` is 1 so `index` starts at -1. This results in `names` not always being set and throws exception

See screenshot: `var` is `user` but `index` is -1
http://i.imgur.com/Wy0xAHy.png

**Comment by nmihajlovski** [comment]
Thanks for reporting this. The parameters name retrieval turned out to be surprisingly hard, as it depends on the compiler used.

Could you please provide more information about how to reproduce this bug?

Specifying the JDK / compiler used and the method signature will be very helpful.
