### ISSUE TITLE
fix Resp header date messy code

### ISSUE THREAD

**Issue by Haloka** [rapidoid/rapidoid#123]
-- response --
200 OK
Server:  Rapidoid
Date:  ææä¸, 28 å­æ 2017 01:08:34 GMT
Content-Type:  application/json
Content-Length:  4
 

package org.rapidoid.commons.Dates;
```
	public static SimpleDateFormat frmt(String frmt) {
		return new SimpleDateFormat(frmt);
	}
```
to 
```
	public static SimpleDateFormat frmt(String frmt) {
		return new SimpleDateFormat(frmt, java.util.Locale.ROOT);
	}
```

result

 -- response --
200 OK
Server:  Rapidoid
Date:  Wed, 28 Jun 2017 09:30:33 GMT
Content-Type:  application/json
Content-Length:  4

**Comment by nmihajlovski** [comment]
Thanks!
