### ISSUE TITLE
Ability to convert IllegalArgumentException as an HTTP 400 (Bad Request) response

### ISSUE THREAD

**Issue by picaron** [rapidoid/rapidoid#126]
Currently, if we return `null` from a controller, the response is automatically translated to a `404 not found` which is very convenient. However for any thrown errors, the response is converted to a 500 internal server error.

However, when designing a REST API, it is very common that we want to return a 400 Bad Request because the client request parameters are invalid.

It would be more useful if we could simply throw an IllegalArgumentException and have that exception translated to a 400 Bad Request response.

Maybe there is a convenient mechanism for handling this but I looked at all the documentation and the examples and couldn't find any clues on how to implement this is a nice way.

**Comment by nmihajlovski** [comment]
Hi, please take a look at `On.error(...)`. E.g. https://github.com/rapidoid/rapidoid/blob/75e52914e9982d25f7335639a705c89e6be1f249/rapidoid-integration-tests/src/test/java/org/rapidoid/http/CustomizationTest.java#L110

**Comment by picaron** [comment]
Hi, that seems to do what I need
Thanks!

**Comment by picaron** [comment]
Hi @nmihajlovski !

I'm reopening this because using the `On.error(...)` handlers doesn't work when using POJO annotation based controllers.

**Comment by picaron** [comment]
Hi @nmihajlovski ,

Thanks for the fast follow-up

I tried updating to 5.4.1, I still have the same issue. The errors I throw are not handled by my custom handlers.

My POJO controller isn't registered using App.beans, I'm using the `@Controller` annotation. Also the REST endpoint are annotated using @Transaction

**Comment by picaron** [comment]
One more interesting behavior: 

If before setting up my On.error handlers I configure a My.wrappers handler, then my On.error handlers will work 😮

**Comment by nmihajlovski** [comment]
Hi @picaron, I created a new issue for this (#133).

**Comment by picaron** [comment]
Ok thanks for the follow-up @nmihajlovski

I'll close this one then.
