### ISSUE TITLE
Atomic application start-up

### ISSUE THREAD

**Issue by nmihajlovski** [rapidoid/rapidoid#128]
As reported by @picaron, during dependency injection JPA is still not bootstrapped, which makes in inaccessible upon bean initialization.

To resolve this, the PostConstruct-annotated methods should be called after JPA bootstrap, but before HTTP server bootstrap.

**Comment by picaron** [comment]
geez, that was fast ! 👍

**Comment by nmihajlovski** [comment]
Thanks! :)
