### ISSUE TITLE
404 response from http://cdn.jsdelivr.net/rapidoid/5.4.1/

### ISSUE THREAD

**Issue by cosminbasca** [rapidoid/rapidoid#134]
I am getting 404's from http://cdn.jsdelivr.net/rapidoid/5.4.1/
with *Couldn't find the requested release version 5.4.1.*

for the following:
- http://cdn.jsdelivr.net/rapidoid/5.4.1/rapidoid.min.css 
- http://cdn.jsdelivr.net/rapidoid/5.4.1/rapidoid.min.js 
- http://cdn.jsdelivr.net/rapidoid/5.4.1/rapidoid.min.js 
that leads to a cascade of js errors and various rendering styling and interaction issues

**Comment by nmihajlovski** [comment]
JSDelivr had introduced some breaking changes. I am adjusting the CDN URLs...
