### ISSUE TITLE
Unable to pass two or more 'Set-Cookie' headers

### ISSUE THREAD

**Issue by romannikov** [rapidoid/rapidoid#143]
Hi,
I need to set several cookie's values and for that I use 'set-cookie' header:
`
req.response().headers()["Set-Cookie"] = "b=$b; path=/; expires=$format; HttpOnly"
req.response().headers()["Set-Cookie"] = "a=$a; path=/; expires=$format; HttpOnly"
`
`headers()` returns map, so it's obvious that only user_id header is passed.

I also tries to do the same with `req.cookies()` but it has only key-value format and I can not set path, expires and other params.

**Comment by nmihajlovski** [comment]
Hi, please use Resp#cookie:

`Resp cookie(String name, String value, String... extras)`

**Comment by romannikov** [comment]
Hi, thanks for response and response :)
