### ISSUE TITLE
Configuration of log settings has no effect

### ISSUE THREAD

**Issue by picaron** [rapidoid/rapidoid#151]
In my `config.yaml` file, the settings I entered for the `log` section have no effect (they are not taken into consideration)

For example, if I set:

```
log:
  fancy: false
```

Whenever I run the application, I always get the fancy output which does not render well on containerized (dockerized) environments

I am using the latest Rapidoid release (5.4.6)

**Comment by nmihajlovski** [comment]
Thanks for reporting, I am working on this now...

**Comment by picaron** [comment]
thanks for rapid fix @nmihajlovski ! 
😄
