### ISSUE TITLE
Extend transaction context to include serialization

### ISSUE THREAD

**Issue by bokesan** [rapidoid/rapidoid#153]
Returning a JPA entity containing a collection of referenced entities as JSON from a transactional request will fail during serialization if the collection is loaded lazy (which is the default).

The reason is that the entity is not fully instantiated when the handler method returns, and the JPA lazy load will happen only on serialization. But it seems that rapidoid closes the transaction before serializing the results, so Hibernate throws a LazyInitializationException.

[stacktrace.txt](https://github.com/rapidoid/rapidoid/files/1551207/stacktrace.txt)

**Comment by nmihajlovski** [comment]
@bokesan Thanks for reporting this!

**Comment by bokesan** [comment]
@nmihajlovski You're welcome.

I did look at the code to see if there might be an easy fix, and got as far as ``AbstractDecoratingHttpHandler``. There I gave up - changing this will apparently require restructuring around exception handlers, and I'd rather leave that to someone familiar with the code base.

**Comment by nmihajlovski** [comment]
I understand. :) `AbstractDecoratingHttpHandler` is the one of the most complex components in the web layer. I will try to find enough time to fix the bug this week...

**Comment by bokesan** [comment]
I have a workaround (of the "dirty hack" kind), so it's not an extremely critical bug for me. The workaround does cost some performance though, so a fix in the next 1-2 months would be appreciated.

**Comment by nmihajlovski** [comment]
Thanks, I am working on it, but it's good to know that!

**Comment by bokesan** [comment]
I can't get 5.5.1 to work. 5.5.0 is fine (except for the transaction behavior), but with 5.5.1 even the simplest requests time out and result in an empty response. In fact, handlers are not called at all - I have a /test handler that only does `Log.info(...)` and `resp.html("Ok!")`, and don't get either the log message or any response.

**Comment by nmihajlovski** [comment]
Thanks for informing me, and I apologize for this embarrassing regression, which was introduced by the recent refactoring of the job executors (all the tests were passing because they were already initializing those executors).

As soon as I confirm the fix, I will release v5.5.2...

**Comment by bokesan** [comment]
Now I see another breaking change: I'm using `resp.json(*entity*)`. In 5.5.0 this serialized *entity* into the response body. In 5.5.2 I always get `"DONE"` as the response body.

**Comment by nmihajlovski** [comment]
I fixed that, I am releasing v5.5.3 now...

**Comment by bokesan** [comment]
Sorry for taking so long about this. The issue itself is fixed, but I am using `@Version` columns, and the change led to the JSON containing the old value, as the serialization happens inside the transaction. Can't have it both ways though, so I finally decided that using JPA.flush() to fix this is acceptable.

**Comment by nmihajlovski** [comment]
Thanks for the feedback!
