### ISSUE TITLE
Can't use JPA.save() to create new objects with number as identifier

### ISSUE THREAD

**Issue by hboelke** [rapidoid/rapidoid#163]
```java
Item item = new Item();
JPA.save(item);
``` 
```java
@Entity
@Table(name = "items")
public class Item {

    @Id
    private long id;
    
    // more code
}
```

Since an id with type byte,short,int,long is always 0 if it's only decalred, jpa always tries to update.
Because:

```java
public <E> E save(E entity) {
	Object id = getIdentifier(entity);
	if (id == null) {
		return insert(entity);
	} else {
		return update(entity);
	}
}
```

I know there is the JPA.insert() method, but is it possible to get the JPA.save() method for new objects with numbers as identifier working too?

**Comment by nmihajlovski** [comment]
`GeneratedValue` caused the problem, indeed. I tested locally, didn't find other problems.
