### ISSUE TITLE
Is it possible to change http.timeout per route or per request?

### ISSUE THREAD

**Issue by bokesan** [rapidoid/rapidoid#189]
I have some routes where it is normal for processing to take some time and so I need to increase the config parameter `http.timeout` to more than the default 30 seconds. But most routes, I'd be happier to have it much lower (say 5 seconds). I've not found anything in the API - it this possible?

**Comment by nmihajlovski** [comment]
Sorry, currently it is not possible to configure the timeout per route nor request.

**Comment by bokesan** [comment]
Ok, thanks. I'll just use a higher default value.
