### ISSUE TITLE
Better documentation, overview

### ISSUE THREAD

**Issue by WhiteTrashLord** [rapidoid/rapidoid#29]
Rapidoid looks very promising to me. Do you plan to add a better documentation on the website?

For example some features that you support blocking and non blocking mode.

I might want to test rapidoid-http-fast soon. It's already possible to set how many cores should be used and some other settings like max. buffer size?

**Comment by huysamen** [comment]
+1 for more complete documentation.

**Comment by nmihajlovski** [comment]
Hi, I am happy to hear about your interest about Rapidoid.

Improving the documentation is the next thing on my to-do list. This weekend I will start adding more examples for the http-fast module and more information about the architecture of the web server and the request processing.

Regarding the configuration options - yes, they are supported, but not documented (like many other things). This weekend I will add documentation about the configuration options, as well...

**Comment by previousdeveloper** [comment]
+1

**Comment by sotoup** [comment]
+1

**Comment by nmihajlovski** [comment]
I am closing this issue, but I will continue improving the docs. :)
