### ISSUE TITLE
Add support for PATCH  HTTP method

### ISSUE THREAD

**Issue by jacek99** [rapidoid/rapidoid#30]
Had a look at the On class:

https://github.com/rapidoid/rapidoid/blob/4893a8f7f8d55af80a996b26558884ff4150fceb/rapidoid-http-fast/src/main/java/org/rapidoid/http/fast/On.java

and it seems to only have support for initial HTTP methods, in particular PUT for updates.

Please add support for the newer PATCH HTTP method as well. Thanks

http://restcookbook.com/HTTP%20Methods/patch/

**Comment by nmihajlovski** [comment]
Thanks for pointing this out, I will add the missing HTTP verbs (PATCH, HEAD and TRACE).

**Comment by nmihajlovski** [comment]
Resolved and already available in the release 5.0.5.
