### ISSUE TITLE
Support second admin port

### ISSUE THREAD

**Issue by jacek99** [rapidoid/rapidoid#31]
All the modern micro-service frameworks like Dropwizard or Spring Boot support opening up a second admin HTTP port.

That port is closed off on the firewall, so not accessible from the outside.

On the admin port, the apps are then safe to expose admin APIs (e.g. refresh internal memory caches, etc) as well as service health check APIs.

See
http://www.dropwizard.io/0.9.1/docs/manual/core.html#health-checks

It would be great if Rapidoid allowed exposing a second admin port + allowed defining REST APIs on it.

Maybe something like AdminOn, a mirror copy of the On class, but for the admin port?

This is a missing piece from making Rapidoid truly producton-ready.

**Comment by nmihajlovski** [comment]
This is important, indeed.

Currently it is possible to simply start multiple servers on different ports in the same app.

But for this admin use case - few extras (like way of easy authentication and simple but proper API) will be useful.

**Comment by nmihajlovski** [comment]
This is done with the Admin.* API, which is a mirror of the On.* API.
The default role required for the "Admin.*" routes is "administrator".
By default, the Admin server will be the same as the On server, which is convenient for simple scenarios, when 1 server is enough.
Configuring a custom admin.port will cause a separate server to be started.
The Admin API isn't documented yet...

**Comment by axel22** [comment]
Is there an example that shows how to start (and later shutdown) multiple server instances that use different ports?

Thanks!

**Comment by nmihajlovski** [comment]
Hi, here is such example:

```java
Setup setup1 = Setup.create("foo").port(2222);
Setup setup2 = Setup.create("bar").port(3333);

setup1.get("/").plain("hi1");
setup2.get("/").json(() -> U.map("msg","hi2"));

HTTP.get("http://localhost:2222/").print(); // test foo
HTTP.get("http://localhost:3333/").print(); // test bar

setup1.shutdown();
setup2.shutdown();
```
Regards!

**Comment by axel22** [comment]
Awesome, thank you.
And thank you for this amazing project!

On July 8, 2016 2:54:59 AM GMT+02:00, Nikolche Mihajlovski <notifications@github.com> wrote:
>Hi, here is such example:
>
>```java
>Setup setup1 = Setup.create("foo").port(2222);
>Setup setup2 = Setup.create("bar").port(3333);
>
>setup1.get("/").plain("hi1");
>setup2.get("/").json(() -> U.map("msg","hi2"));
>
>HTTP.get("http://localhost:2222/").print(); // test foo
>HTTP.get("http://localhost:3333/").print(); // test bar
>
>setup1.shutdown();
>setup2.shutdown();
>```
>Regards!
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/rapidoid/rapidoid/issues/31#issuecomment-231249245

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nmihajlovski** [comment]
You are welcome! :)
