### ISSUE TITLE
Get rid of the "bullshit" statement

### ISSUE THREAD

**Issue by jacek99** [rapidoid/rapidoid#33]
It may seem cool, but it does deter corporate users from taking Rapidoid seriously.

This type of language is generally frowned upon  when folks like me are trying to present a framework to managers. It strikes them as immature.

I recommend something like "easy and super fast" :-)

Just a suggestion to help with Rapidoid adoption.

**Comment by wenerme** [comment]
+ 1

**Comment by mirovalent** [comment]
+1

**Comment by jfernand** [comment]
-1 Irrelevant

**Comment by nmihajlovski** [comment]
I agree the "no-bullshit" is controversial, so I am going to change it soon to something nicer...

Thank you all for the feedback!

**Comment by nmihajlovski** [comment]
Changed to "Extremely Fast, Simple and Powerful Java Web Framework!". :)
