### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by rpmoore** [rapidoid/rapidoid#34]
At first glance the one thing that would prevent me from using this today is the lack of HTTPS support.  The framework looks really promising and I think adding HTTPS support would encourage others to start to use the framework.

**Comment by zaregis** [comment]
+1

**Comment by Turbots** [comment]
I'm really liking the framework so far, extremely fast and intuitive to use.
Adding HTTPS support is the last major hurdle before people can start using it in production.

**Comment by tcha8595** [comment]
+1 to HTTPS support. Can't be used without it for our applications. Having to add a reverse proxy in front means slowing it down for some cases.

**Comment by diziourov** [comment]
+1 and also it would be great if it has good and secure configuration by default (e.g.: [https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility]).

**Comment by nkev** [comment]
How about a fully automated HTTPS setup using https://letsencrypt.org/ 
That would surely make this framework standout as irresistable ;) 
There is a cool web server project written in Go called [Caddy](https://github.com/mholt/caddy) that does this really well.

**Comment by osrashwan** [comment]
+1

**Comment by nmihajlovski** [comment]
Unfortunately, the HTTPS support couldn't make it into v5.1. :(
