### ISSUE TITLE
Why fast-http has no url pattern support ?

### ISSUE THREAD

**Issue by wenerme** [rapidoid/rapidoid#35]
url pattern is really important for doing some real thing,I don't want to use web for only url pattern it's to heavy.

As sweet as 

```
On.get("/user/${id}").json(req->"You id "+req.params().get("id"))
```

**Comment by kliakos** [comment]
Just tested this feature and I realized that path params exist within the same Map as URL params. This off course cause the obvious problem that if a URL parameter with the same name is passed, there is a conflict.

Assuming I have the following route:

```java
		On.get("/books/{book_id}").json((Req req) -> {
			System.out.println(JSON.stringify(req.params()));

			return "book";
		});
```

And call this URL http://localhost:8888/books/1234?book_id=4567, I get:
`{"book_id":"1234"}`

The URL param is gone.

I don't want to have to worry about name confict however.

My suggestion is for path params to have their own Map and separate method for retrieving the from the Req object.

**Comment by kliakos** [comment]
On the other hand many web server frameworks have implemented the path params mixed with the URL params. Sometimes it helps, sometimes not. Not sure which path should this framework follow.

**Comment by sebyx07** [comment]
really looking forward for this

**Comment by wenerme** [comment]
I will use rapidoid again when fast-http has url pattern.

@kliakos How about follow JXS-RS's url pattern.

**Comment by kliakos** [comment]
@wenerme my notice was not about the pattern itself, it was about how the path params are accessed and how they are distinguished from the URL params.

**Comment by wenerme** [comment]
I think JAX-RS spec answered `how patterns are distinguished from the URL params`,but the api change is unavoidable.
