### ISSUE TITLE
Package scanning excludes a lot of common packages, breaks example 9

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [rapidoid/rapidoid#36]
I wanted to try out example 9, "Hello world" RESTful service (high-level POJO abstraction). Since I'm in Germany I put my code in a package structure that starts with `de.`. But the classpath scanner excludes packages that start with `de` by default (and a lot more countries, see "scan-ignore.txt`). I'm not sure what the reasoning behind this is? The example didn't work for me like that.

**Comment by nmihajlovski** [comment]
Thanks for reporting this! The packages from the list are ignored to speed-up the classpath scanning process.

This makes sense for some libraries that are unlikely to use Rapidoid's classpath scanner on their own (e.g. org.hibernate, org.springframework).

But, the simplest way to initially create such list was automatically from the open-source libraries, but it was so big (and by now low-priority), that I never revised it manually.

I will prune it in some of the next minor releases, and keep only the packages that are unlikely to use Rapidoid classpath scanner.

**Comment by nmihajlovski** [comment]
Actually, I completely removed the list of ignored packages. Ignoring some packages was a bad idea, due to the surprises it caused.

Now all the packages will be scanned, unless a target package is specified.

**Comment by FrontierPsychiatrist** [comment]
Cool, thanks!
