### ISSUE TITLE
Hot reloading of changed classes

### ISSUE THREAD

**Issue by nmihajlovski** [rapidoid/rapidoid#38]

**Comment by adam-arold** [comment]
Do you have any idea when will this be ready? Does it involve JRebel integration somehow?

**Comment by nmihajlovski** [comment]
This will be ready soon (max. 1 week). It won't use any external tools, just a customized class reloader and a watcher for file system changes.

**Comment by adam-arold** [comment]
Do you need some help? Will itt support JRebel?

**Comment by nmihajlovski** [comment]
Thanks and no worries, I am on it... ;) It should work well with JRebel, too, but we will need to do some testing when it's ready...

**Comment by nmihajlovski** [comment]
Apologies for the incorrect estimation, the 5.1.0 release will take more time than expected.

**Comment by sebyx07** [comment]
awesome job. I will soon start a web framework for jruby and want to use rapidoid for the http

**Comment by adam-arold** [comment]
So how do I use it with JRebel?
