### ISSUE TITLE
Support for Chunked Transfer Encoding

### ISSUE THREAD

**Issue by nmihajlovski** [rapidoid/rapidoid#40]
It would be nice to add support for Chunked Transfer Encoding in the HTTP server.

**Comment by cosminbasca** [comment]
@nmihajlovski any progress on this issue? It would be very useful to have chunked transfer encoding handled by rapidoid as well. Thanks !

**Comment by nmihajlovski** [comment]
Hi, I didn't make any progress on this yet... It has lower priority since most of the users don't need it.

**Comment by cosminbasca** [comment]
Hi @nmihajlovski thanks for the reply, I understand. Looking forward to seeing support for this in future versions of rapidoid.
