### ISSUE TITLE
Browser serves constantly scrolling page instead of the 500 error page?

### ISSUE THREAD

**Issue by nmihajlovski** [rapidoid/rapidoid#42]
I has been reported that in some error cases the browser serves constantly scrolling page instead of the 500 error page.

How can this scenario be reproduced?

**Comment by peterps-health** [comment]
Please close, as after tryi reproduce it for some time can't reproduce it myself.
Seems like a newby mistake, thank you for raising it through.

**Comment by nmihajlovski** [comment]
Thanks again for your feedback.

The exception handling got improved in the 5.0.10 release.
