### ISSUE TITLE
Integration with Dependency Injection frameworks

### ISSUE THREAD

**Issue by yterradas** [rapidoid/rapidoid#49]
hi, 

the documentation shows examples of `@Inject` but that is a Rapidoid custom Inject and between 2 `@Controller`s which do not have any complex dependencies.  could you show an example of using Guice, Dagger, or some other DI framework?  if those are not supported then how is dependency injection supported?  

thank you

**Comment by procek69** [comment]
Hi,

You don't need Guice, neither Dagger for DI, just put @Inject before a field (could and may be private one) inside controller, service etc.
To power your code all you need are two annotations: @Singleton and @Service.

**Comment by asafm** [comment]
@procek69 That's a bit too much to say. There are lot of thing to control when using a DI. I don't see any reason why this framework won't support Guice or Spring. It should be a simple interface which provides an implementation of the Controller class, which then rapidoid will do its magic to transform it into a RequestHandler. 
I don't understand the motivation to develop your own implementation of DI in the library.

We tried integrating with Guice and failed to understand how to do that easily. The inject module was too complex to understand.

**Comment by yterradas** [comment]
@procek69 injection of private fields is an anti-pattern because it hides dependencies thus making tests impossible without exposing such fields.  does rapidoid's DI support integration with other DIs?

**Comment by nmihajlovski** [comment]
It is already possible to provide any controller to Rapidoid, like in this example:
http://www.rapidoid.org/high-level-annotation-based-pojo-controllers.html

This approach allows the users to manage the components however they like, but it is not an elegant way to integrate with the DI frameworks.

In the upcoming v5.3 release there will be generic API for integration with any DI framework (and also built-in integration for Guice):
```java
/**
 * A collection of beans, usually managed in external dependency injection context.
 */
public interface Beans {

	<T> T get(Class<T> type);

	Set<Object> getAll();

	Set<Object> getAnnotated(Collection<Class<? extends Annotation>> annotations);

}

```

Please take a look at the referenced commits, any feedback would be highly appreciated.
