### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by tuddman** [rapidoid/rapidoid#51]
any plans to add websocket support?

perhaps leverage http://java-websocket.org/

**Comment by nmihajlovski** [comment]
Implementing WebSocket server using Rapidoid Net is planned as Google Summer of Code project idea (if Rapidoid gets accepted).

**Comment by picaron** [comment]
is this still on the dev roadmap?

**Comment by nmihajlovski** [comment]
Sorry, trying to implement the WebSocket protocol would increase Rapidoid's scope too much.

**Comment by boussou** [comment]
https://javalibs.com/artifact/org.rapidoid/rapidoid-websocket
