### ISSUE TITLE
req.uri() only returns path with query string

### ISSUE THREAD

**Issue by kliakos** [rapidoid/rapidoid#53]
The req.uri() method only returns the path with query string.

We usually refer to the URI as the entire URL of the request.

My expectation would be to return the entire URL, since there already are path() and query() methods to achieve what the uri() does.

What is your opinion?

**Comment by nmihajlovski** [comment]
Apologies @kliakos for the very late answer on this.
I think it's good for uri() to remain as it is, and I will consider adding url() in future to return the entire URL.
