### ISSUE TITLE
HTTP header keys and values should not be url-decoded

### ISSUE THREAD

**Issue by pepri** [rapidoid/rapidoid#55]
I have issue when comparing Authorization HTTP header value that contains Base64-encoded string. I found out that the value contains a plus sign that is being converted to a space.

~~~java
String authorization = req.header("authorization", null);
~~~

Currenty, HTTP header keys and values are url-decoded in [FastHttp.java](https://github.com/rapidoid/rapidoid/blob/861c011e76d5a220f65abc5f7f6cc1f71b892ba9/rapidoid-http-fast/src/main/java/org/rapidoid/http/FastHttp.java#L118). I think that the HTTP header keys and values should not be url-decoded as defined in [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.4).

**Comment by nmihajlovski** [comment]
Thanks for reporting this, I fixed it.
