### ISSUE TITLE
ElasticSearch support to invoke clients methods

### ISSUE THREAD

**Issue by GuillerDark** [rapidoid/rapidoid#58]
I'm trying to use elasticsearch inside of the framework but when use http fast restful to create web services and the project have dependencies of elastic it can not invoke the methods of elastic, always crash in the invoke() method in the class Cls.java, i'm searching about this issue but i can't find anything about it, forgive me that it is my mistake but im been trying everything

**Comment by GuillerDark** [comment]
Settings settings = Settings.settingsBuilder()
        .put("client.transport.sniff", true).build();
TransportClient client = TransportClient.builder().settings(settings).build();

exactly when i call the .build() method on TransportClient builder, Rapidoid can't invoke the method and always crash

**Comment by korri123** [comment]
Hey, can you paste the stacktrace from the exception you get?

**Comment by GuillerDark** [comment]
i use the 1.7 version of elastic that does not use .build() in the transport client and its work fine, but with the 2.0 and up version have the issue, i loss the stacktrace because with the version I managed to overcome the problem

**Comment by nmihajlovski** [comment]
Hi, this problem doesn't look related to Rapidoid.

The exception that you see in Cls.invoke is probably caused by some other exception occurring in the "build" method.

Also, the .build()-caller code shouldn't be inside a web handler, please try running it before the setup of RESTful services.

**Comment by GuillerDark** [comment]
The .build() method is call outside the web handler, but Rapidoid is the one that makes that call on startup invoke to load the init variables like the transport client and others databases clients, also the .builder() is a native elastic method that does not make problems outside rapidoid implementation, the both projects are separated, and works fine when elastic project is standalone, but when i do the implementation in Rapidoid is where the issues appear.

**Comment by nmihajlovski** [comment]
Can you please provide a simple code that demonstrates this issue?
