### ISSUE TITLE
Header keys should be case-insensitive

### ISSUE THREAD

**Issue by pepri** [rapidoid/rapidoid#61]
Header key should be case-insensitive when getting header value.

Both values should be same in this case:
~~~java
String value1 = req.header("authorization", null);
String value2 = req.header("Authorization", null);
~~~

RFC 7230 states: "Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace."

**Comment by nmihajlovski** [comment]
Thanks for reporting, I fixed it.
