### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by procek69** [rapidoid/rapidoid#73]
Hi,

I didn't find any information about mechanism of JWT authentication.
Anyway, when I study about cookiepack(), I think the JWT and the Rapidoid's cookies and roles system are very similar.

Am I right?

**Comment by nmihajlovski** [comment]
Hi, yes, the mechanism is similar, the cookiepack stores encrypted and signed data, which can be exchanged with a cookie or a "_token" request parameter.

BTW, the "cookiepack" name was a bad naming choice, it will be renamed to "token" in v5.2.0...

**Comment by procek69** [comment]
Thanks
