### ISSUE TITLE
No annotations found on Windows

### ISSUE THREAD

**Issue by bokesan** [rapidoid/rapidoid#75]
On Windows, `scan.ClasspathUtil` never finds any classes. Log info is always:

    INFO org.rapidoid.scan.ClasspathUtil - Finished classpath scan | time = xxms | search = 0 | found = []

The same jar works fine under Linux.

I think the reason might be using `File.separatorChar` to search in jars (ClasspathUtil.java line 288 in the main branch). This is correct in the filesystem, but `zipEntry.getName()` always returns forward slashes, so `name.startsWith` (line 318) always fails.

**Comment by nmihajlovski** [comment]
That was the cause of the problem, indeed. Thanks!

**Comment by bokesan** [comment]
Updated to 5.1.9. Fix works. Thanks!
