### ISSUE TITLE
url prefix support for rapidoid?

### ISSUE THREAD

**Issue by cosminbasca** [rapidoid/rapidoid#77]
if it possible to specify a url prefix for rapidoid? This can be useful when running a rapidoid instance proxied via apache under a different prefix. The problem occurs when the response is produced with  GUI.page(...). The internal js and css resources cannot be loaded under the correct prefixed path. A global config option specifying the prefix would be great...

**Comment by nmihajlovski** [comment]
I apologize for the late reply.

There is "app.contextPath" configuration entry introduced already, but it's not used/supported in most of the GUI pages, only in the scaffolding GUI.

This is an important issue and I will take care of it soon...

**Comment by cosminbasca** [comment]
Thanks a lot @nmihajlovski ! That would be great :+1:
