### ISSUE TITLE
JPA cannot find entities

### ISSUE THREAD

**Issue by hulian** [rapidoid/rapidoid#79]
10:49:00.728 [com.example.Application.main()] INFO  org.rapidoid.jpa.JPAUtil - Didn't find JPA entities, canceling JPA/Hibernate setup!

I use maven plugin to exec application , but it show this message , and JPA is not working.

-------------------------------------------------------------------------------------------
Application.java

package com.example;

import org.rapidoid.annotation.Valid;
import org.rapidoid.jpa.JPA;
import org.rapidoid.setup.App;
import org.rapidoid.setup.On;

public class Application {

	
	public static void main(String[] args) {
		
		App.bootstrap(args).jpa();
      
		On.get("/books").json(() -> JPA.of(Book.class).all()); // get all books

		On.post("/books").json((@Valid Book b) -> JPA.save(b)); // insert new book

		On.put("/books/{id}").json((Long id, @Valid Book b) -> JPA.update(b)); // update (replace) book

		On.delete("/books/{id}").json((Long id) -> { // delete book
			JPA.delete(Book.class, id);
			return true;
		});
 
		
	}
}

----------------------------------------------------------------------------------------------

Book.java
@Entity
public class Book {

	@Id
	@GeneratedValue
	public Long id;

	@NotNull
	public String title;

	public int year;

}

Here is my pom.xml:
---------------------------------------------------------------------

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.javatech</groupId>
	<artifactId>rapidoid_test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	
	

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.rapidoid</groupId>
			<artifactId>rapidoid-quick</artifactId>
			<version>5.1.9</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>com.example.Application</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

full information
--------------------------------------------------
10:49:00.578 [com.example.Application.main()] INFO  org.rapidoid.setup.App - Inferring application root | main = com.example.Application | package = com.example
10:49:00.581 [com.example.Application.main()] INFO  org.rapidoid.scan.ClasspathUtil - Scanning classpath | annotated = [@Controller, @Service, @Run, @Named, @Singleton] | packages = [com.example]
10:49:00.582 [com.example.Application.main()] INFO  org.rapidoid.scan.ClasspathUtil - Finished classpath scan | time = 1ms | searched = 0 | found = []
10:49:00.621 [com.example.Application.main()] INFO  o.r.config.RapidoidInitializer - Starting Rapidoid... | version = 5.1.9 | mode = production | profiles = [default] | process = 6420@DESKTOP-835KTD4 | java = 1.8.0_91 | dir = C:\Users\admin\workspace\rapidoid_test
10:49:00.725 [com.example.Application.main()] INFO  org.rapidoid.util.Msc - --------------------------------
10:49:00.725 [com.example.Application.main()] INFO  org.rapidoid.util.Msc - Bootstrapping JPA (Hibernate)...
10:49:00.725 [com.example.Application.main()] INFO  org.rapidoid.util.Msc - --------------------------------
10:49:00.725 [com.example.Application.main()] INFO  org.rapidoid.scan.ClasspathUtil - Scanning classpath | annotated = [@Entity] | packages = [com.example]
10:49:00.727 [com.example.Application.main()] INFO  org.rapidoid.scan.ClasspathUtil - Finished classpath scan | time = 2ms | searched = 0 | found = []
10:49:00.728 [com.example.Application.main()] INFO  org.rapidoid.jpa.JPAUtil - Didn't find JPA entities, canceling JPA/Hibernate setup!
10:49:00.821 [server] INFO  o.r.net.impl.RapidoidServerLoop - Server started | address = 0.0.0.0 | port = 8888 | I/O workers = 8 | accept = non-blocking
10:49:01.263 [com.example.Application.main()] INFO  o.rapidoid.http.impl.HttpRoutesImpl - Registering handler | setup = app | verbs = GET | path = /books | roles = [] | tx = NONE | handler = json(() -> ...)
10:49:01.301 [com.example.Application.main()] INFO  o.rapidoid.http.impl.HttpRoutesImpl - Registering handler | setup = app | verbs = POST | path = /books | roles = [] | tx = NONE | handler = json((Book b) -> ...)
10:49:01.304 [com.example.Application.main()] INFO  o.rapidoid.http.impl.HttpRoutesImpl - Registering handler | setup = app | verbs = PUT | path = /books/{id} | roles = [] | tx = NONE | handler = json((Long id, Book b) -> ...)
10:49:01.306 [com.example.Application.main()] INFO  o.rapidoid.http.impl.HttpRoutesImpl - Registering handler | setup = app | verbs = DELETE | path = /books/{id} | roles = [] | tx = NONE | handler = json((Long id) -> ...)

**Comment by thhart** [comment]
Why closed silently? What was the resolution? I have the same problem, I guess it is a classpath problem when the entities not reside in the main package.

**Comment by thhart** [comment]
I had to scan my custom package in advance like this:

```
      App.scan("xxx.xxx.xxx.xxx");
      App.bootstrap(args).jpa(); // bootstrap JPA

```
