### ISSUE TITLE
Make configurable the merge of json body into data

### ISSUE THREAD

**Issue by elaatifi** [rapidoid/rapidoid#80]
First of all thanks for making this server.

from HttpParser.parsePosted
```        
public void parsePosted(Buf input, KeyValueRanges headersKV, BufRange rBody, KeyValueRanges posted,
	                        Map<String, List<Upload>> files, RapidoidHelper helper, Map<String, Object> dest) {

		boolean completed = parseBody(input, headersKV, rBody, posted, files, helper);

		posted.toUrlEncodedParams(input, dest);

		if (!completed && !rBody.isEmpty()) {
			try {
				Map<String, Object> jsonData = JSON.parse(input.get(rBody), Map.class);
				if (jsonData != null) {
					dest.putAll(jsonData);
				}
			} catch (Exception e) {
				Log.warn("The attempt to parse the request body as JSON failed. Please specify the correct content type in the request header!", e);
			}
		}
	}
```
Can we make it configurable if we want to bypass this part, and control how JSON will be parsed. it does not have sense to parse it twice. for example there is the simple case when we want to parse JSON as a custom type.
_I'm forced right now to use unknown content type in client request to skip this part (to force completed to be true) which is ugly :)_

**Comment by nmihajlovski** [comment]
Hi, currently the API doesn't support such customization, but I am working on it now...

**Comment by nmihajlovski** [comment]
So, in v5.2 it will be easily customizable, and lazy by default.

**Comment by elaatifi** [comment]
Oh cool ! thanks again for the great work :)

**Comment by nmihajlovski** [comment]
Sure, I am happy to work on Rapidoid. Thank you!
