### ISSUE TITLE
Include 404 error handling in ErrorHandler instead of HttpIO.write404

### ISSUE THREAD

**Issue by elaatifi** [rapidoid/rapidoid#81]
Hello,

One thing that can be enhanced is to include the 404 kinds of errors in ErrorHandler.
in the current state HttpIO.write404 hard code this process. I think it's practical to delegate this to ErrorHandler

All we can do now is to override 404,html in the templates  path.
But we should be able to customize this process i.e. using another template engine, customize the locale or other things

**Comment by nmihajlovski** [comment]
Hi, currently the "not found" cases can be handled with a default generic handler, e.g. `On.req(....)`, which gets executed when no other handler matches the route.

I agree about delegating this to the ErrorHandler with a special exception (e.g. NotFound). I will add support for this in v5.2.0 or a bit later...

Thanks for your feedback!
