### ISSUE TITLE
Bad request on '..' in GET query parameter

### ISSUE THREAD

**Issue by mooman219** [rapidoid/rapidoid#82]
Going to a valid route with a query parameter that has ".." in it will result in a bad request even though it's completely valid.

For example, `http://localhost:8888/Auth?code=test..` will fail with a bad request, while `http://localhost:8888/Auth?code=test.` will properly route. The handler in question was registered with `On.get("/Auth").plain(new ReqRespHandler() { ... etc`. The error is coming from this segment of code, https://github.com/rapidoid/rapidoid/blob/933fc5003295a0f121243856e9a0263ddb200a34/rapidoid-buffer/src/main/java/org/rapidoid/bytes/BytesUtil.java#L571.

Unfortunately, a google api I'm using returns a token with '..' present in the string. When using google oauth, the redirect link gets passed a get parameter that has `somekey=abcdabcd..abcda&` in it. Therefore, I would consider this a bug on Rapidoid's part as that's a valid URL. The fix would involve removing the if statement causing the fail and updating the corresponding tests associated with '..' not being valid.

**Comment by korri123** [comment]
This also happens when you try to put @ in the uri

**Comment by mooman219** [comment]
> This also happens when you try to put @ in the uri

Looks right, the @ character is missing here, failing the request: https://github.com/rapidoid/rapidoid/blob/933fc5003295a0f121243856e9a0263ddb200a34/rapidoid-buffer/src/main/java/org/rapidoid/bytes/BytesUtil.java#L39

Medium uses @ iirc, I'm not sure where there are all of these limitations imposed through Rapidoid. I've seen sites use // in their url as well, which is blocked under Rapidoid currently. I switched to a different web framework for a project I'm working on because of this.

**Comment by korri123** [comment]
You can just override the class (by copy pasting it including the package information), don't have to switch frameworks over this.

**Comment by mooman219** [comment]
It's just a prototype, which is why I chose Rapidoid in the first place. I just moved to another nonbiased web framework in the mean time.

**Comment by mooman219** [comment]
Specifically, the characters "(tab) ; / ? : @ = &" are reserved and normally shouldn't be in the url under normal cases. Unfortunately, there are many offenders that include google, wordpress, medium, and many others. A separate issue report should probably be opened for that since it's out of spec. The issue I'm having is in spec and should not be failing under normal circumstances.

**Comment by korri123** [comment]
According to [this](https://tools.ietf.org/html/std66#section-3.3) @ is not reserved though.

**Comment by mooman219** [comment]
It is under this https://tools.ietf.org/html/std66#section-2.2

**Comment by nmihajlovski** [comment]
When I developed this, increasing the security through such URI limitations (not allowing '/../') seemed like a good idea. For most users this turned out not to be a problem, but when it becomes a problem, I am sure it is frustrating.

I will fix this soon (v5.2 will be released these days), and I will move the security checks to a higher level.

Thanks @mooman219 for raising the issue, and thanks @korri123 for your help and involvement!

**Comment by mooman219** [comment]
When I get a request with a get parameter that happens to have '..' in it, it should be allowed; '/../' is totally fair to disallowed. When using google oauth, the redirect link gets passed a get parameter that has "somekey=abcdabcd..abcda&" in it, which Rapidoid fails to handle and produces a "bad request".

**Comment by nmihajlovski** [comment]
Thanks for clarifying, somehow I had missed the "query parameter" part of the issue description.

**Comment by mooman219** [comment]
Thanks for the update.
As for validating the URL in the first place, it seems more complex than Rapidoid allows for. For example, http://example.com/document/?uri=http://user:password@example.com/?foo=bar is valid, since "/" and "?" do not need to be percent encoded in query strings, and neither do ":" and "@" according to the spec.

I think a larger rework of the URI validation would need to be put in place to allow for the large surface area of valid URIs. In the mean time, is there a way to avoid the check in the first place without recompiling Rapidoid?

**Comment by nmihajlovski** [comment]
Sure, I am currently working on the other chars like "@".

I am afraid it's not currently possible to avoid the check without recompiling. Sorry about that.
