### ISSUE TITLE
JDBI integration - ClassCastException on hot reload with possibe fix

### ISSUE THREAD

**Issue by korri123** [rapidoid/rapidoid#83]
I am using JDBI with Rapidoid.

**The problem**
When visiting a page that makes database bindings/mapping after hot reloading I get a ClassCastException.
`java.lang.ClassCastException: is.kormakur.site.dao.EntryDao cannot be cast to is.kormakur.site.dao.EntryDao`

**How it happens**
After some Googling I figured out it has something to do with mismatched ClassLoaders, because JDBI holds a cache of the bindings/map of a DAO class for the database table.

**My personal fix**
If I hot reload and visit some other page before ever loading the offending page that initially maps the Pojo to the table and does database calls, then the problem is fixed, I can hot reload after freely without any exceptions.

**Potential fix**
When Rapidoid initializes it should use the same ClassLoader as it does for hot reloading as it uses initially, if I understand the problem correctly.

If you need some more information, like maybe an example project feel free to ask.

**Comment by nmihajlovski** [comment]
Hi, thanks for reporting and investigating this issue.

The same problem occurred with Hibernate and Morphia, and I "solved" it by not hot-reloading the changed entity classes.

Once a class is loaded, it can't be reloaded with the same class loader. So, Rapidoid uses a new class loader for each hot reload, which provides a good isolation between different reloading life-cycles.

So, when a hot reload happens, some classes are actually not reloaded:
- all Rapidoid classes,
- JPA entities,
- Morphia entities,
- (the fix of this bug will add the JDBI DAOs to this list).

**Comment by nmihajlovski** [comment]
P.S. Sure, it would be great if you can provide a simple example project.

**Comment by korri123** [comment]
Hmm, is there a public method in Rapidoid that does this, so the process is more flexible?

The strange thing is that I could avoid the issue by hot reloading/compiling a random class before creating the entity objects. I was going to hack a fix to this by using reflection to invoke private method App.restartApp() but since that method actually invokes the main method again it just created an endless loop.

Also, JDBI itself doesn't provide Daos, but interfaces that allow you to map objects from a resultset. There is a premade class that uses reflection to do this automatically for all your fields.

I'll give you an example project in a bit!

**Comment by korri123** [comment]
Sorry, after experimenting with creating an example project I discovered that the bug was on my end.

**Comment by korri123** [comment]
Well, the bug is still there, but it happens because I use a custom method to bind the classes using reflection instead of beans, which JDBI uses by default. It doesn't happen if you use theirs.

I still think it's worth looking into why hot reloading everything and then running the method that maps the table into the entity fixes the problem, it might fix it entirely without needing to check for annotations.

**Comment by korri123** [comment]
Discovered something else, projects are essentially hot reloaded before the server restarts the web application. I hot reloaded a class, adding a System.out.println() and refreshed the page before Rapidoid detected the change and it essentially worked. Then it restarted the application and the ClassCastException occured. (I had not applied my personal fix)

**Comment by korri123** [comment]
I have discovered that, at least for me, using IntelliJ IDEA, I override App.java, disable calling App.restartApp() and then hot reload freely without it restarting the application. I am using IntelliJ's built in function Reload Changed Classes in the Run menu. I'm not sure if IDEA is doing the reloading for me or not. This fixes the error.

**Comment by nmihajlovski** [comment]
@korri123 JDBI integration is unlikely to be supported by Rapidoid in foreseeable future. I am closing this one...
