### ISSUE TITLE
Path param in @Controller

### ISSUE THREAD

**Issue by procek69** [rapidoid/rapidoid#84]
Feature: Similiar mechanism like in HTTP annotations:

`@GET("/{id}/subresources")`

but also in

`@Controller("/api/resource/{id}/subresource")`

**Comment by korri123** [comment]
Where would the parameters go? would it be mapped to e.g. `int id` as in your case?

**Comment by nmihajlovski** [comment]
This is already implemented in v5.2. :)

**Comment by nmihajlovski** [comment]
E.g. the following code will register a handler for `/api/resource/{id}/subresource/abc`:

```java
@Controller("/api/resource/{id}/subresource")
public class Ctrl {

	@GET
	public String abc(String id) {
		return id;
	}

}

```

**Comment by korri123** [comment]
Ah, I see.
By the way I think it's time to update the TechEmpower benchmarks to more realistic Rapidoid code, they [marked it as stripped](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/rapidoid), also some people are accusing it of being [misleading](https://www.reddit.com/r/java/comments/4yfkat/which_java_web_framework_is_more_userfriendly/d6npilw?context=3).

**Comment by korri123** [comment]
[Stripped](https://groups.google.com/forum/?fromgroups=#!topic/framework-benchmarks/h4IFSXmuATo) means that it will be hidden by default.

**Comment by nmihajlovski** [comment]
Thanks, I am aware of the problem, I plan to implement the benchmarks using the high-level API very soon...
