### ISSUE TITLE
Dependency Injection into constructor

### ISSUE THREAD

**Issue by assafey** [rapidoid/rapidoid#86]
Is it possible to @Inject into c'tor with rapidoid?
I am getting error "org.rapidoid.setup.PojoHandlersSetup - Couldn't process bean: class server.controllers.UserController"

Where:

```
@Controller
public class UserController {

    private final UserService userService;

    @Inject
    public UserController(UserService userService) {
        this.userService = userService;
    }
}
```

```
@Service
public class UserService {
}
```

**Comment by nmihajlovski** [comment]
Sorry, this hasn't been implemented yet.
