### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [rapidoid/rapidoid#89]
# Hello @nmihajlovski ,

I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the main file need to be grab on [github](https://github.com/rapidoid/rapidoid).
Are the main files all under `assets/rapidoid/` this folder?(`rapidoid-extras.css` and `rapidoid-extras.js`)
And are there any other dependency files needed to be grab?
Please help me confirm this.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8398

**Comment by nmihajlovski** [comment]
Hi @kennynaoh ,

Thank you, it would be great to have Rapidoid hosted on cdnjs!

There are 2 files that need to be hosted: `rapidoid.min.js` and `rapidoid.min.css`.
They are in the `rapidoid-html/src/main/resources/default/static` folder.

Best regards!

**Comment by kennynaoh** [comment]
@nmihajlovski Thanks!

**Comment by kennynaoh** [comment]
Hello @nmihajlovski ,
I found that the `rapidoid.min.js` and `rapidoid.min.css` don't exist in some of old versions under `rapidoid-html/src/main/resources/default/static` this folder. (`4.1.0`~`5.1.0` and `rapidoid-0.9.0`~`rapidoid-4.0.3`)
Please help me confirm that.
Thanks for your help!

**Comment by nmihajlovski** [comment]
Yes, that is correct.
In the previous versions they existed in the `rapidoid-html/src/main/resources/rapidoid/static` folder.
Thank you again!

**Comment by kennynaoh** [comment]
Thanks!
How about `rapidoid-1.0.1` and `rapidoid-1.0.0`? I can't find it under `rapidoid-html`.
And it doesn't exist `rapidoid-html` this folder in `rapidoid-0.9.0`.
Please help me confirm that.
Thanks for your help!

**Comment by nmihajlovski** [comment]
That's correct, it doesn't exist in the early versions.

**Comment by kennynaoh** [comment]
So what files I need to grab in those versions
(`rapidoid-0.9.0`, `rapidoid-1.0.0`, `rapidoid-1.0.1`)
Thanks!

**Comment by nmihajlovski** [comment]
No JavaScript /CSS files were produced in these early versions.
(In the early period Rapidoid had only a back-end development framework.)

So, please ignore those versions that are missing rapidoid-html.

Thank you again!

**Comment by kennynaoh** [comment]
Thanks!
