### ISSUE TITLE
Server response with 404 about 30 seconds.

### ISSUE THREAD

**Issue by IRus** [rapidoid/rapidoid#94]
Hi

I tried org.rapidoid:rapidoid-quick:5.2.5 and `CustomHttpServer` from tutorial. It's works fine until we send request with responses with HTTP 404:

```
time curl 'http://localhost:8080/' -H 'Host: localhost:8080' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Upgrade-Insecure-Requests: 1' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
Content-Length: 10

Not found!
real    0m32.690s
user    0m0.008s
sys 0m0.008s
```

This is very strange. Looks like connection not closed because of keep-alive.

**Comment by IRus** [comment]
@nmihajlovski hi, do you have time to take a look at this?

**Comment by nmihajlovski** [comment]
Thanks for reporting the bug, and sorry for the late response. :(

There was an extra empty line in the pre-constructed HTTP response.
