### ISSUE TITLE
Missing utf-8 charset in json response header

### ISSUE THREAD

**Issue by panchekhin** [rapidoid/rapidoid#97]
According to http://www.rapidoid.org/rendering-a-http-response.html calling Resp json(...) sets Content-Type: application/json; charset=utf-8. But it doesn't set charset=utf-8 actually.
I suppose this is because of error in MediaType class:
public static final MediaType APPLICATION_JSON = create("application/json", "json", "map");
(call to create instead of createUTF8)

**Comment by nmihajlovski** [comment]
Thanks for reporting this.

Actually the documentation was not updated, so I corrected it. The `utf-8` encoding is implicit for the `application/json` content type.

**Comment by ivanviragine** [comment]
@nmihajlovski how can I set the charset using this kind of construction: 

`On.get("/opengraph/").json((String url) -> OpenGraph.i().getOpenGraphObjectFromUrl(url));`

?

**Comment by nmihajlovski** [comment]
You can also have the response as parameter, e.g. `(String uri, Resp json) -> ...`

**Comment by ivanviragine** [comment]
Thanks for the reply @nmihajlovski !

Since lambdas expects parameters of the same type, I can't do that.
Or am I missing something?
